require("plugins_config.lsp_config")
require("plugins_config.treesitter")
require("plugins_config.telescope")
require("plugins_config.neotree")
require("plugins_config.color_preview")
require("plugins_config.bufferline")
